[source]
type = "N2N"
address = ["Tcp", "relays-new.cardano-mainnet.iohk.io:3001"]
magic = "mainnet"

[sink]
type = "Webhook"
# Linux:
# url = "http://172.17.0.1:8095/incorrect_webhook"

# Docker Desktop:
url = "http://host.docker.internal:8095/incorrect_webhook"

[sink.retry_policy]
max_retries = 100
backoff_unit =  1000
backoff_factor = 1
max_backoff = 100000
