[source]
type = "N2N"
address = ["Tcp", "relays-new.cardano-mainnet.iohk.io:3001"]
magic = "mainnet"

[sink]
type = "Terminal"
throttle_min_span_millis = 500
wrap = true

[cursor]
type = "File"
path = "/config/mainnet.cursor"
