[source]
type = "N2N"
address = ["Tcp", "relays-new.cardano-mainnet.iohk.io:3001"]
magic = "mainnet"

[sink]
type = "Webhook"
# Linux:
# url = "http://172.17.0.1:8095/webhook"

# Docker Desktop:
url = "http://host.docker.internal:8095/webhook"

[source.mapper]
include_block_end_events = true
include_transaction_details = true
include_transaction_end_events = true
include_block_cbor = true
include_byron_ebb = true