[source]
type = "N2N"
address = ["Tcp", "relays-new.cardano-mainnet.iohk.io:3001"]
magic = "mainnet"

[metrics]
address = "0.0.0.0:9186"
endpoint = "/metrics"

[sink]
type = "Terminal"
throttle_min_span_millis = 500
wrap = true
