[source]
type = "N2N"
address = ["Tcp", "relays-new.cardano-mainnet.iohk.io:3001"]
magic = "mainnet"

[source.intersect]
type = "Origin"

[source.finalize]
until_hash = "aa83acbf5904c0edfe4d79b3689d3d00fcfc553cf360fd2229b98d464c28e9de"

[[filters]]
type = "Selection"

[filters.check]
predicate = "variant_in"
argument = ["Block"]

[sink]
type = "Terminal"
throttle_min_span_millis = 500
wrap = true