##
## PREPROD
##
## TCP configuration for local testing.

[source]
type = "N2N"
address = ["Tcp", "preprod-node.world.dev.cardano.org:30000"]
magic = "preprod"
since = [13438856, "50767455ecc51099eb9b966f0a1f1c238fbe4530f98931aed51bdf2209e24150"] # 2022-10-22 13:00
min_depth = 12

[cursor]
type = "File"
path = "oura_cursor"

[source.mapper]
include_block_end_events = false
include_transaction_details = true
include_transaction_end_events = false
include_block_cbor = false
include_byron_ebb = false

[[filters]]
type = "Selection"

[filters.check]
predicate = "variant_in"
argument = ["Block","Transaction","RollBack"]

[sink]
type = "Terminal"
throttle_min_span_millis = 500
wrap = true
